"""add google calendar fields to user

Revision ID: 1a921e2aec7a
Revises: 37186ab913b0
Create Date: 2026-05-13 21:17:10.509315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a921e2aec7a'
down_revision: Union[str, None] = '37186ab913b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('google_refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_calendar_sync', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_calendar_sync')
    op.drop_column('users', 'google_refresh_token')
    # ### end Alembic commands ###
